from .gradient_based import cross_entropy_loss, mse_loss, grad_cross_entropy, grad_mse
from .predictive_coding import predictive_coding_cross_entropy, predictive_coding_mse
from .hebbian import contrastive_update, hebbian_update
from .feedback_alignment import feedback_alignment_cross_entropy, feedback_alignment_mse